import type { Restaurant, Table, WaitlistEntry } from '../types';

export const INITIAL_RESTAURANT: Restaurant = {
  id: 'rest-001',
  name: 'Le Bistro MaitreQ',
  slug: 'le-bistro-maitreq',
  phone: '+1 (555) 342-9800',
  address: '452 Downtown Ave, Culinary District',
  created_at: new Date(Date.now() - 3600000 * 24 * 30).toISOString(),
};

export const INITIAL_TABLES: Table[] = [
  { id: 'tbl-1', restaurant_id: 'rest-001', table_number: 'T1', capacity: 2, status: 'OCCUPIED', current_party_id: 'entry-seated-1', current_guest_name: 'David Chen', updated_at: new Date(Date.now() - 30 * 60000).toISOString() },
  { id: 'tbl-2', restaurant_id: 'rest-001', table_number: 'T2', capacity: 2, status: 'AVAILABLE', updated_at: new Date().toISOString() },
  { id: 'tbl-3', restaurant_id: 'rest-001', table_number: 'T3', capacity: 4, status: 'AVAILABLE', updated_at: new Date().toISOString() },
  { id: 'tbl-4', restaurant_id: 'rest-001', table_number: 'T4', capacity: 4, status: 'OCCUPIED', current_party_id: 'entry-seated-2', current_guest_name: 'Sophia Patel', updated_at: new Date(Date.now() - 45 * 60000).toISOString() },
  { id: 'tbl-5', restaurant_id: 'rest-001', table_number: 'T5', capacity: 4, status: 'RESERVED', updated_at: new Date(Date.now() - 10 * 60000).toISOString() },
  { id: 'tbl-6', restaurant_id: 'rest-001', table_number: 'T6', capacity: 6, status: 'AVAILABLE', updated_at: new Date().toISOString() },
  { id: 'tbl-7', restaurant_id: 'rest-001', table_number: 'T7', capacity: 6, status: 'OCCUPIED', current_party_id: 'entry-seated-3', current_guest_name: 'Marcus Vance', updated_at: new Date(Date.now() - 50 * 60000).toISOString() },
  { id: 'tbl-8', restaurant_id: 'rest-001', table_number: 'T8', capacity: 8, status: 'AVAILABLE', updated_at: new Date().toISOString() },
  { id: 'tbl-9', restaurant_id: 'rest-001', table_number: 'B1 (Booth)', capacity: 4, status: 'AVAILABLE', updated_at: new Date().toISOString() },
  { id: 'tbl-10', restaurant_id: 'rest-001', table_number: 'B2 (Booth)', capacity: 4, status: 'OCCUPIED', current_party_id: 'entry-seated-4', current_guest_name: 'Elena Rostova', updated_at: new Date(Date.now() - 20 * 60000).toISOString() },
];

export const INITIAL_WAITLIST: WaitlistEntry[] = [
  {
    id: 'entry-001',
    restaurant_id: 'rest-001',
    guest_name: 'Sarah Jenkins',
    phone_number: '+1 (555) 234-5678',
    party_size: 2,
    notes: 'Anniversary celebration. Prefers quiet booth if possible.',
    status: 'NOTIFIED',
    public_token: 'sarah-j-9821',
    position: 1,
    estimated_wait_minutes: 5,
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    notified_at: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: 'entry-002',
    restaurant_id: 'rest-001',
    guest_name: 'Alex Rivera',
    phone_number: '+1 (555) 876-5432',
    party_size: 4,
    notes: 'High chair needed for toddler.',
    status: 'WAITING',
    public_token: 'alex-r-4312',
    position: 2,
    estimated_wait_minutes: 15,
    created_at: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: 'entry-003',
    restaurant_id: 'rest-001',
    guest_name: 'Maya Lin',
    phone_number: '+1 (555) 345-6789',
    party_size: 2,
    notes: 'Outdoor patio preferred if open.',
    status: 'WAITING',
    public_token: 'maya-l-7734',
    position: 3,
    estimated_wait_minutes: 25,
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'entry-004',
    restaurant_id: 'rest-001',
    guest_name: 'Michael Sterling',
    phone_number: '+1 (555) 901-2345',
    party_size: 6,
    notes: 'Birthday dinner with family.',
    status: 'WAITING',
    public_token: 'michael-s-1120',
    position: 4,
    estimated_wait_minutes: 40,
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'entry-seated-1',
    restaurant_id: 'rest-001',
    table_id: 'tbl-1',
    guest_name: 'David Chen',
    phone_number: '+1 (555) 456-7890',
    party_size: 2,
    notes: 'Seated at Table T1',
    status: 'SEATED',
    public_token: 'david-c-5591',
    position: 0,
    estimated_wait_minutes: 0,
    created_at: new Date(Date.now() - 60 * 60000).toISOString(),
    notified_at: new Date(Date.now() - 35 * 60000).toISOString(),
    seated_at: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'entry-seated-2',
    restaurant_id: 'rest-001',
    table_id: 'tbl-4',
    guest_name: 'Sophia Patel',
    phone_number: '+1 (555) 678-9012',
    party_size: 4,
    notes: 'Seated at Table T4',
    status: 'SEATED',
    public_token: 'sophia-p-8823',
    position: 0,
    estimated_wait_minutes: 0,
    created_at: new Date(Date.now() - 80 * 60000).toISOString(),
    notified_at: new Date(Date.now() - 50 * 60000).toISOString(),
    seated_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 'entry-cancelled-1',
    restaurant_id: 'rest-001',
    guest_name: 'Robert Fox',
    phone_number: '+1 (555) 123-9999',
    party_size: 3,
    notes: 'Changed plans',
    status: 'CANCELLED',
    public_token: 'robert-f-0041',
    position: 0,
    estimated_wait_minutes: 0,
    created_at: new Date(Date.now() - 95 * 60000).toISOString(),
  }
];
