# Generated by Django 6.1 on 2026-09-01 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🧹', max_length=50)),
                ('chore_type', models.CharField(choices=[('ROUTINE', 'Daily Routine'), ('BOUNTY', 'Bounty Board')], default='ROUTINE', max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('ONE_OFF', 'One-off')], default='DAILY', max_length=10)),
                ('reward_money', models.DecimalField(decimal_places=2, default=1.0, help_text='Allowance earned in $', max_digits=6)),
                ('reward_xp', models.PositiveIntegerField(default=50, help_text='XP earned for completion')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['chore_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child')], default='CHILD', max_length=10)),
                ('avatar', models.CharField(default='🦁', help_text='Avatar emoji or icon name', max_length=50)),
                ('pin', models.CharField(blank=True, help_text='4-digit PIN for parent approval access', max_length=4, null=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('allowance_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('current_streak', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChoreSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='proofs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Needs Rework')], default='PENDING', max_length=10)),
                ('parent_note', models.TextField(blank=True, help_text='Feedback note from parent', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='chores.familymember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='chores.familymember')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='chore',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Leave blank for open bounty chores', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chores', to='chores.familymember'),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('required_xp', models.PositiveIntegerField(default=0)),
                ('required_streak', models.PositiveIntegerField(default=0)),
                ('members', models.ManyToManyField(blank=True, related_name='badges', to='chores.familymember')),
            ],
        ),
    ]
